// Generated by CoffeeScript 1.4.0
(function() {
  var Afnic, Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base").base;

  Afnic = (function(_super) {

    __extends(Afnic, _super);

    function Afnic() {
      return Afnic.__super__.constructor.apply(this, arguments);
    }

    Afnic.prototype.negative = function() {
      return "No entries found in the AFNIC Database.";
    };

    Afnic.prototype.positive = function() {
      return "status:      ACTIVE";
    };

    Afnic.prototype.request = function() {
      return this.domain + '\r\n';
    };

    Afnic.prototype.failure = function() {
      return "Too many requests...";
    };

    return Afnic;

  })(Base);

  exports.afnic = Afnic;

}).call(this);
