// Generated by CoffeeScript 1.7.1
(function() {
  var Base, Pir,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base").base;

  Pir = (function(_super) {
    __extends(Pir, _super);

    function Pir() {
      return Pir.__super__.constructor.apply(this, arguments);
    }

    Pir.prototype.negative = function() {
      var domain;
      domain = this.domain.toUpperCase();
      return "NOT FOUND|No match for \"" + domain + "\"";
    };

    Pir.prototype.positive = function() {
      var domain;
      domain = this.domain.toUpperCase();
      return "Domain Name:" + domain;
    };

    Pir.prototype.request = function() {
      return "FULL " + this.domain + '\r\n';
    };

    Pir.prototype.failure = function() {
      return "WHOIS LIMIT EXCEEDED";
    };

    return Pir;

  })(Base);

  exports.pir = Pir;

}).call(this);
