// Generated by CoffeeScript 1.7.1
(function() {
  var Base, Standard,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base").base;

  Standard = (function(_super) {
    __extends(Standard, _super);

    function Standard() {
      return Standard.__super__.constructor.apply(this, arguments);
    }

    return Standard;

  })(Base);

  exports.standard = Standard;

}).call(this);
