// Generated by CoffeeScript 1.7.1
(function() {
  var Base, Uniregistry,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base").base;

  Uniregistry = (function(_super) {
    __extends(Uniregistry, _super);

    function Uniregistry() {
      return Uniregistry.__super__.constructor.apply(this, arguments);
    }

    Uniregistry.prototype.request = function() {
      var domain;
      domain = this.domain.toLowerCase();
      return domain + '\r\n';
    };

    Uniregistry.prototype.negative = function() {
      return "is available for registration";
    };

    Uniregistry.prototype.positive = function() {
      var domain;
      domain = this.domain.toLowerCase();
      return "Domain Name: " + domain;
    };

    return Uniregistry;

  })(Base);

  exports.uniregistry = Uniregistry;

}).call(this);
