// Generated by CoffeeScript 1.7.1
(function() {
  var Base, Verisign,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base").base;

  Verisign = (function(_super) {
    __extends(Verisign, _super);

    function Verisign() {
      return Verisign.__super__.constructor.apply(this, arguments);
    }

    return Verisign;

  })(Base);

  exports.verisign = Verisign;

}).call(this);
